spring:
  datasource:
    url: jdbc:mysql://192.168.10.10:3306/tb_stock?characterEncoding=utf-8&useSSL=false
    username: root
    password: 199747
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka-headless.default:8888/eureka,http://eureka-1.eureka-headless.default:8888/eureka,http://eureka-2.eureka-headless.default:8888/eureka
